
import type { Berry, BerryFirmness, BerryFlavor } from './berries';
import type { ContestEffect, ContestType, SuperContestEffect } from './contests';
import type { EncounterCondition, EncounterConditionValue, EncounterMethod } from './encounters';
import type { EvolutionChain, EvolutionTriggers } from './evolution';
import type { Generation, Pokedex, Version, VersionGroup } from './games';
import type { Item, ItemAttribute, ItemCategory, ItemFlingEffect, ItemPocket } from './items';
import type { Location, LocationArea, PalParkArea, Region } from './locations';
import type { Machine } from './machines';
import type { Move, MoveAliment, MoveBattleStyle, MoveCategory, MoveDamageClass, MoveLearnMethod, MoveTarget } from './moves';
import type { Ability, Characteristic, EggGroup, Gender, GrowthRate, Nature, PokeathlonStat, Pokemon, PokemonColor, PokemonForm, PokemonHabitat, PokemonShape, PokemonSpecies } from './pokemon';

export type ResourceMap = {
  'berry': Berry;
  'berry-firmness': BerryFirmness;
  'berry-flavor': BerryFlavor;
  'contest-type': ContestType;
  'contest-effect': ContestEffect;
  'super-contest-effect': SuperContestEffect;
  'encounter-method': EncounterMethod;
  'encounter-condition': EncounterCondition;
  'encounter-condition-value': EncounterConditionValue;
  'evolution-chain': EvolutionChain;
  'evolution-triggers': EvolutionTriggers;
  'generation': Generation;
  'pokedex': Pokedex;
  'version': Version;
  'version-group': VersionGroup;
  'item': Item;
  'item-attribute': ItemAttribute;
  'item-category': ItemCategory;
  'item-fling-effect': ItemFlingEffect;
  'item-pocket': ItemPocket;
  'location': Location;
  'location-area': LocationArea;
  'pal-park-area': PalParkArea;
  'region': Region;
  'machine': Machine;
  'move': Move;
  'move-aliment': MoveAliment;
  'move-battle-style': MoveBattleStyle;
  'move-category': MoveCategory;
  'move-damage-class': MoveDamageClass;
  'move-learn-method': MoveLearnMethod;
  'move-target': MoveTarget;
  'ability': Ability;
  'characteristic': Characteristic;
  'egg-group': EggGroup;
  'gender': Gender;
  'growth-rate': GrowthRate;
  'nature': Nature;
  'pokeathlon-stat': PokeathlonStat;
  'pokemon': Pokemon;
  'pokemon-color': PokemonColor;
  'pokemon-form': PokemonForm;
  'pokemon-habitat': PokemonHabitat;
  'pokemon-shape': PokemonShape;
  'pokemon-species': PokemonSpecies;
};

export type Resource = keyof ResourceMap;
